### ISSUE TITLE
Heroku Error: Cannot find module

### ISSUE THREAD

**Issue by DogsGamer** [allangrds/Localiza-IASD#49]
I can not add zombie.js in Heroku can anyone help me?

> 2018-12-21T20:02:19.947495+00:00 heroku[worker.1]: Starting process with command `node bot.js`
2018-12-21T20:02:20.764417+00:00 heroku[worker.1]: State changed from starting to up
2018-12-21T20:02:24.519063+00:00 heroku[worker.1]: State changed from up to crashed
2018-12-21T20:02:24.501418+00:00 heroku[worker.1]: Process exited with status 1
2018-12-21T20:02:24.428696+00:00 app[worker.1]: internal/modules/cjs/loader.js:583
2018-12-21T20:02:24.428737+00:00 app[worker.1]:     throw err;
2018-12-21T20:02:24.428739+00:00 app[worker.1]:     ^
2018-12-21T20:02:24.428741+00:00 app[worker.1]: 
2018-12-21T20:02:24.428742+00:00 app[worker.1]: Error: Cannot find module 'zombie'
2018-12-21T20:02:24.428749+00:00 app[worker.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
2018-12-21T20:02:24.428751+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
2018-12-21T20:02:24.428758+00:00 app[worker.1]:     at Module.require (internal/modules/cjs/loader.js:637:17)
2018-12-21T20:02:24.428760+00:00 app[worker.1]:     at require (internal/modules/cjs/helpers.js:22:18)
2018-12-21T20:02:24.428761+00:00 app[worker.1]:     at Object.<anonymous> (/app/bot.js:2:17)
2018-12-21T20:02:24.428763+00:00 app[worker.1]:     at Module._compile (internal/modules/cjs/loader.js:689:30)
2018-12-21T20:02:24.428764+00:00 app[worker.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
2018-12-21T20:02:24.428765+00:00 app[worker.1]:     at Module.load (internal/modules/cjs/loader.js:599:32)
2018-12-21T20:02:24.428767+00:00 app[worker.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
2018-12-21T20:02:24.428768+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by allangrds** [comment]
I'm sorry DogsGamer , but this repo isn't for Heroku questions.
